name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Gradle Wrapper & Build APK
        run: |
          # چونکہ gradlew فائل مسنگ ہے، ہم خود گریڈل ریپ کریں گے تاکہ بلڈ چل سکے
          gradle wrapper
          
          # پرمیشن دینا اور فائنل اے پی کے بلڈ کرنا
          chmod +x gradlew
          ./gradlew assembleDebug
          
          # فائل کو آرٹفیکٹ کے لیے الگ فولڈر میں منتقل کرنا
          mkdir -p output_apk
          find . -name "app-debug.apk" -exec cp {} output_apk/smart_timetable.apk \;

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Timetable-APK
          path: output_apk/smart_timetable.apk
          ./gradlew assembleDebug
          
          # اے پی کے فائل کو گٹ ہب کے مین فولڈر میں منتقل کرنا تاکہ ڈاؤن لوڈ ہو سکے
          mkdir -p $GITHUB_WORKSPACE/output_apk
          find . -name "app-debug.apk" -exec cp {} $GITHUB_WORKSPACE/output_apk/smart_timetable.apk \;

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Timetable-APK
          path: output_apk/smart_timetable.apk
          
